
-- Generated by ORDS REST Data Services 18.4.0.r3541002
-- Schema: ACE2G3  Date: Wed May 22 05:27:18 2019 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ACE2G3',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'ace2g3',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'ace3g2.proyecto',
      p_base_path      => '/duchapp/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => 'Servicio restful para el proyecto final de ace2 grupo 3');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'contacto',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Agrega un contacto a la agenda');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'contacto',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => 'Agrega un contacto a la lista de contactos o agenda',
      p_source         => 
'DECLARE
    nIdcontacto number;
BEGIN
    BEGIN
        SELECT IDUSUARIO
        INTO nIdcontacto
        FROM USUARIO
        WHERE CORREO = :CORREO
        ;
    END;

    INSERT INTO AGENDA (IDUSUARIO, IDCONTACTO)
    VALUES (:IDUSUARIO, nIdcontacto);
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'contacto',
      p_method             => 'POST',
      p_name               => 'correo',
      p_bind_variable_name => 'correo',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Correo del contacto a agregar');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'contacto',
      p_method             => 'POST',
      p_name               => 'idusuario',
      p_bind_variable_name => 'idusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id de usuario dueño de la agenda');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'contactos/:idusuario',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Devuelve los contactos de un usuario');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'contactos/:idusuario',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Devuelve la lista de contactos de un usuario',
      p_source         => 
'select IDCONTACTO
, CORREO
, NOMBRE
, PROMEDIOTOTAL
, PROMEDIOEFECTIVO
from VW_REGPROMEDIOAGENDA
where idusuario = :idusuario
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'contactos/:idusuario',
      p_method             => 'GET',
      p_name               => 'idusuario',
      p_bind_variable_name => 'idusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id de usuario del que se quiere obtener su lista de contactos');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'login/:username/:password',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Inicio de sesion de usuario');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'login/:username/:password',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Servicio de inicio de sesion',
      p_source         => 
'select idusuario, correo, nombre, apellido
from usuario
where correo = :username
and clave = HASH_MD5(:password)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'login/:username/:password',
      p_method             => 'GET',
      p_name               => 'password',
      p_bind_variable_name => 'password',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Contraseña del usuario');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'login/:username/:password',
      p_method             => 'GET',
      p_name               => 'username',
      p_bind_variable_name => 'username',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Nombre de usuario correspondiente al correo electronico');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promedio/:idusuario',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Promedio general de los registros de ducha por usuario');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promedio/:idusuario',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Devuelve el registro promedio de las lecturas de un usuario',
      p_source         => 
'SELECT    IDUSUARIO
        , PROMEDIOTOTAL
        , PROMEDIOEFECTIVO
        , PROMEDIOLITROS
  FROM VW_REGPROMEDIO
 WHERE IdUsuario = :idusuario
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'promedio/:idusuario',
      p_method             => 'GET',
      p_name               => 'dusuario',
      p_bind_variable_name => 'dusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id de usuario del que se desea el promedio total');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promedioagenda/:idusuario',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Promedios de los usuarios de la agenda de contactos');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promedioagenda/:idusuario',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Deveuelve los promedios e información de los contactos de la agenda del usuario',
      p_source         => 
'SELECT IDCONTACTO
     , CORREO
     , NOMBRE
     , PROMEDIOTOTAL
     , PROMEDIOEFECTIVO
     , TRUNC(PROMEDIOLITROS, 1) PROMEDIOLITROS
 FROM VW_REGPROMEDIOAGENDA
WHERE IDUSUARIO = :idusuario');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'promedioagenda/:idusuario',
      p_method             => 'GET',
      p_name               => 'idusuario',
      p_bind_variable_name => 'idusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id del usuario dueño de la agenda de contactos');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promediodia/:idusuario/:fecha',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Devuelve el promedio para un dia en una fecha especifica');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promediodia/:idusuario/:fecha',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Devuelve el promedio para un dia en una fecha especifica, la fecha es en formato YYYYMMDD <año><mes><dia>',
      p_source         => 
'SELECT     IDUSUARIO
        ,  FECHA
        ,  PROMEDIOTOTAL
        ,  PROMEDIOEFECTIVO
        ,  PROMEDIOLITROS
 FROM VW_REGPROMEDIO_DIA
WHERE IDUSUARIO = :idusuario
  AND FECHA     = :fecha');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'promediodia/:idusuario/:fecha',
      p_method             => 'GET',
      p_name               => 'fecha',
      p_bind_variable_name => 'fecha',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Fecha de la que se quiere el promedio para un usuario especifico, la fecha tiene el formato YYYYMMDD, <año><mes><dia>');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'promediodia/:idusuario/:fecha',
      p_method             => 'GET',
      p_name               => 'idusuario',
      p_bind_variable_name => 'idusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id del usuario del que se desea el promedio del dia especificado');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promediomensual/:idusuario/:anio/:mes',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Muestra el promedio de un mes de un año dado para un usuario especifico');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'promediomensual/:idusuario/:anio/:mes',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Muestra el promedio de un mes de un año dado para un usuario especifico',
      p_source         => 
'SELECT    IDUSUARIO
        , ANIO
        , MES
        , PROMEDIOTOTAL
        , PROMEDIOEFECTIVO
        , PROMEDIOLITROS
  FROM VW_REGPROMEDIO_ANIOMES
WHERE IDUSUARIO = :idusuario
  AND (ANIO = :anio OR :anio = 0)
  AND (MES = :mes   OR :mes  = 0)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'promediomensual/:idusuario/:anio/:mes',
      p_method             => 'GET',
      p_name               => 'anio',
      p_bind_variable_name => 'anio',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Año del que se desea el promedio, si el valor es 0 se toman todos los años');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'promediomensual/:idusuario/:anio/:mes',
      p_method             => 'GET',
      p_name               => 'idusuario',
      p_bind_variable_name => 'idusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id de usuario que se desea el promedio');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'promediomensual/:idusuario/:anio/:mes',
      p_method             => 'GET',
      p_name               => 'mes',
      p_bind_variable_name => 'mes',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Mes del que se desea el promedio si el valor es 0 se toman todos los meses');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'registro',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Inserta un nuevo registro de lectura de tiempo de baño');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'registro',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => 'Inserta un nuevo registro de lectura de tiempo de baño',
      p_source         => 
'BEGIN
    INSERT INTO REGISTRO(IDUSUARIO, FECHA, TIEMPOTOTAL, TIEMPOEFECTIVO, LITROS)
    VALUES (:idusuario, systimestamp + interval ''-6'' hour, :tiempototal, :tiempoefectivo, :litros);
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'registro',
      p_method             => 'POST',
      p_name               => 'idusuario',
      p_bind_variable_name => 'idusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id de usuario al que se agregara el registro obtenido');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'registro',
      p_method             => 'POST',
      p_name               => 'litros',
      p_bind_variable_name => 'litros',
      p_source_type        => 'URI',
      p_param_type         => 'DOUBLE',
      p_access_method      => 'IN',
      p_comments           => 'Cantidad de litros utilizados durante el baño');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'registro',
      p_method             => 'POST',
      p_name               => 'tiempoefectivo',
      p_bind_variable_name => 'tiempoefectivo',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Tiempo efectivo de baño en segundos');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'registro',
      p_method             => 'POST',
      p_name               => 'tiempototal',
      p_bind_variable_name => 'tiempototal',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Tiempo total de baño en segundos');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'registros/:idusuario',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Registros de un usuario especifico');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'registros/:idusuario',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Registros de un usuario especifico',
      p_source         => 
'SELECT    IDREGISTRO
        , TO_CHAR(FECHA, ''DD/MM/YYYY'') FECHA
        , TO_CHAR(FECHA, ''HH:MI:SS'') HORA
        , TIEMPOTOTAL
        , TIEMPOEFECTIVO
        , IDUSUARIO
        , LITROS
FROM REGISTRO
WHERE IDUSUARIO = :idusuario
ORDER BY FECHA');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'registros/:idusuario',
      p_method             => 'GET',
      p_name               => 'idusuario',
      p_bind_variable_name => 'idusuario',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => 'Id de usuario que se desean los registros');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'signin',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Agrega un usuario');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'signin',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => 'Agrega un nuevo usuario',
      p_source         => 
'BEGIN
    INSERT INTO USUARIO (CORREO, NOMBRE, APELLIDO, CLAVE)
    VALUES (:CORREO, :NOMBRE, :APELLIDO, :CLAVE);
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'signin',
      p_method             => 'POST',
      p_name               => 'apellido',
      p_bind_variable_name => 'apellido',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Apellido del usuario puede ser nulo');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'signin',
      p_method             => 'POST',
      p_name               => 'clave',
      p_bind_variable_name => 'clave',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Contraseña del usuario');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'signin',
      p_method             => 'POST',
      p_name               => 'correo',
      p_bind_variable_name => 'correo',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Correo unico del usuario que lo identifica en la aplicacion');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'ace3g2.proyecto',
      p_pattern            => 'signin',
      p_method             => 'POST',
      p_name               => 'nombre',
      p_bind_variable_name => 'nombre',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Nombre del usuario');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'usuarios',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Devuelve todos los usuarios registrados en la aplicacion');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ace3g2.proyecto',
      p_pattern        => 'usuarios',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 0,
      p_mimes_allowed  => '',
      p_comments       => 'Devuelve todos los usuarios registrados en la aplicacion',
      p_source         => 
'SELECT    idusuario
        , correo
        , nombre
        , apellido
        , clave
FROM usuario
');

    
        
COMMIT;

END;